
services:
  app:
    build:
      context: .
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    ports:
      - "9000:9000"
    networks:
      - app

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app

networks:
  app:
