# Version 4.0

name: "${APP_NAME}"

services:

    # Laravel

    cms:
        build:
            context: .
        volumes:
            - ./cms:/var/www/html/cms
            - ./public:/var/www/html/public
            - ./.env:/var/www/html/.env
        working_dir: /var/www/html/cms
        networks:
            - laravel
        container_name: "${APP_NAME}_cms"

    # Laravel front-end

    cms-frontend:
        image: node:20-alpine
        volumes:
            - ./cms/resources:/var/www/html/cms/resources
            - ./public:/var/www/html/public
            - ./.env:/var/www/html/cms/resources/.env
        working_dir: /var/www/html/cms/resources
        ports:
            - "11${APP_ID}:11${APP_ID}"
        command: sh -c "npm install && npm run dev"
        container_name: "${APP_NAME}_cms-front"

    # Web front-end

    web-frontend:
        image: node:20-alpine
        volumes:
            - ./web:/var/www/html/web
            - ./public:/var/www/html/public
            - ./.env:/var/www/html/web/.env
        working_dir: /var/www/html/web
        ports:
            - "12${APP_ID}:12${APP_ID}"
        command: sh -c "npm install && npm run dev"
        container_name: "${APP_NAME}_web-front"

    # Nginx proxy

    nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./cms:/var/www/html/cms
            - ./public:/var/www/html/public
        working_dir: /var/www/html
        ports:
            - "10${APP_ID}:80"
        depends_on:
            - cms
        networks:
            - laravel
        container_name: "${APP_NAME}_nginx"

    # Backend database

    mariadb:
        image: mariadb:11.1
        ports:
            - "13${APP_ID}:3306"
        environment:
            MARIADB_DATABASE: ${APP_NAME}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: art3dRoot
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
        container_name: "${APP_NAME}_db"

networks:
    laravel:

volumes:
    db_data:
